app:
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: true # 控制显示版本更新提示，如果 false，则不接受新版本提示

crawler:
  request_interval: 1000 # 请求间隔(毫秒)
  enable_crawler: true # 是否启用爬取新闻功能，如果 false，则直接停止程序
  use_proxy: false # 是否启用代理，false 时为关闭
  default_proxy: "http://127.0.0.1:10086"

# 🔸 daily（当日汇总模式）
#   • 推送时机：按时推送(默认每小时推送一次)
#   • 显示内容：当日所有匹配新闻 + 新增新闻区域
#   • 适用场景：日报总结、全面了解当日热点趋势
#
# 🔸 current（当前榜单模式）
#   • 推送时机：按时推送(默认每小时推送一次)
#   • 显示内容：当前榜单匹配新闻 + 新增新闻区域
#   • 适用场景：实时热点追踪、了解当前最火的内容
#
# 🔸 incremental（增量监控模式）
#   • 推送时机：有新增才推送
#   • 显示内容：新出现的匹配频率词新闻
#   • 适用场景：避免重复信息干扰

# 推送模式选择
report:
  mode: "daily" # 可选: "daily"|"incremental"|"current"
  rank_threshold: 5 # 排名高亮阈值

notification:
  enable_notification: true # 是否启用通知功能，如果 false，则不发送手机通知
  message_batch_size: 4000 # 消息分批大小（字节）(这个配置别动)
  dingtalk_batch_size: 20000 # 钉钉消息分批大小（字节）(这个配置也别动)
  batch_send_interval: 1 # 批次发送间隔（秒）
  feishu_message_separator: "━━━━━━━━━━━━━━━━━━━" # feishu 消息分割线

  # 🕐 推送时间窗口控制（可选功能）
  # 用途：限制推送的时间范围，避免非工作时间打扰
  # 适用场景：
  #   - 只想在工作日白天接收推送（如 09:00-18:00）
  #   - 希望在晚上固定时间收到汇总（如 20:00-22:00）
  push_window:
    enabled: false  # 是否启用推送时间窗口控制，默认关闭
    # 注意：GitHub Actions 执行时间不稳定，时间范围建议至少留足 2 小时
    # 如果想要精准的定时推送，建议使用 Docker 部署在个人服务器上
    time_range:
      start: "08:00"  # 推送时间窗口开始（北京时间）
      end: "22:00"    # 推送时间窗口结束（北京时间）
    once_per_day: true  # 每天在时间窗口内只推送一次，如果 false，则窗口内每次执行都推送
    push_record_retention_days: 7  # 推送记录保留天数

  # 请务必妥善保管好 webhooks，不要公开
  # 如果你以 fork 的方式将本项目部署在 GitHub 上，请勿在此填写任何 webhooks，而是将 webhooks 填入 GitHub Secret
  # 不然轻则手机上收到奇怪的广告推送，重则存在更严重的安全隐患
  webhooks:
    feishu_url: "https://www.feishu.cn/flow/api/trigger-webhook/c1149d560ebf84bb58c76d504f4c7224" # 飞书机器人的 webhook URL
    dingtalk_url: "" # 钉钉机器人的 webhook URL
    wework_url: "" # 企业微信机器人的 webhook URL
    telegram_bot_token: "" # Telegram Bot Token
    telegram_chat_id: "" # Telegram Chat ID
    email_from: "" # 发件人邮箱地址
    email_password: "" # 发件人邮箱密码或授权码
    email_to: "" # 收件人邮箱地址，多个收件人用逗号分隔
    email_smtp_server: "" # SMTP服务器地址（可选，留空自动识别）
    email_smtp_port: "" # SMTP端口（可选，留空自动识别）
    ntfy_server_url: "https://ntfy.sh" # ntfy服务器地址，默认使用公共服务，可改为自托管地址
    ntfy_topic: "" # ntfy主题名称
    ntfy_token: "" # ntfy访问令牌（可选，用于私有主题）
    # ========== 关键词配置 ==========
  keywords:
  # 1) 市场统称
  - 美股
  - 港股
  - A股
  - 币圈
  - 金融

  # 2) 美股相关
  - 纳斯达克
  - 纽交所
  - 标普500
  - 道琼斯
  - 美联储
  - 加息
  - 降息
  - 非农就业
  - CPI
  - PPI
  - 华尔街

  # 3) 港股相关
  - 恒生指数
  - 恒生科技
  - 港交所
  - 南向资金
  - 港股通

  # 4) A股相关
  - 上证指数
  - 深证成指
  - 创业板指
  - 科创板
  - 北向资金
  - 沪深300
  - 中证500
  - 证监会
  -  IPO
  - 限售股解禁

  # 5) 币圈相关
  - 比特币
  - BTC
  - 以太坊
  - ETH
  - 狗狗币
  - DOGE
  - 稳定币
  - 央行数字货币
  - 区块链
  -  DeFi
  -  NFT
  - 减半
  - 现货ETF

  # 6) 宏观/战略
  - 中美战略
  - 中美博弈
  - 贸易战
  - 关税
  - 制裁
  - 实体清单
  - 对华投资限制
  - 出口管制
  - 去风险
  - 供应链重构
  - 印太经济框架
  - 一带一路
  - 人民币国际化
  - 外汇管制
  - 汇率破7
  - 离岸人民币
  - 外汇储备

  # 7) 政策/监管
  - 降准
  - 降息
  - MLF
  - LPR
  - 逆回购
  - 财政政策
  - 货币政策
  - 金融监管
  - 金融稳定法
  - 资管新规
  - 退市新规
  - 全面注册制

  # 8) 黑天鹅/风险
  - 爆雷
  - 债务违约
  - 硅谷银行
  - 瑞信
  - 银行破产
  - 流动性危机
  - 黑天鹅
  - 灰犀牛
  - 系统性风险

  # 9) 高频热点（动态补充）
  - 人工智能
  -  chatGPT
  - 新能源
  - 光伏
  - 锂电池
  - 电动车
  - 汽车下乡
  - 消费券
  - 房地产救市
  - 保交楼

# 用于让关注度更高的新闻在更前面显示，即用算法重新组合不同平台的热搜排序形成你侧重的热搜，合起来是 1 就行
weight:
  rank_weight: 0.6 # 排名权重
  frequency_weight: 0.3 # 频次权重
  hotness_weight: 0.1 # 热度权重

# name 可以定义任意名称，只具有显示作用，即使项目运行了几天后，忽然改掉 name 也不会影响代码的正常运行
platforms:
  - id: "toutiao"
    name: "今日头条"
  - id: "baidu"
    name: "百度热搜"
  - id: "wallstreetcn-hot"
    name: "华尔街见闻"
  - id: "thepaper"
    name: "澎湃新闻"
  - id: "bilibili-hot-search"
    name: "bilibili 热搜"
  - id: "cls-hot"
    name: "财联社热门"
  - id: "ifeng"
    name: "凤凰网"
  - id: "tieba"
    name: "贴吧"
  - id: "weibo"
    name: "微博"
  - id: "douyin"
    name: "抖音"
  - id: "zhihu"
    name: "知乎"
  - id: "shenchao"
    name: "深潮"
